-- V019__export_jobs.sql
-- Phase 2.10: Asynchronous export job tracking.
--
-- export_jobs: one row per export request.
--   Scope PROJECT: synchronous path — row created, processed immediately,
--     COMPLETED in the same request; file_data holds the generated bytes.
--   Scope ZONE / PAN_INDIA: asynchronous path — row created (QUEUED),
--     processed by ExportJobProcessor (@Async), COMPLETED when ready.
--
-- file_data (bytea) holds the generated Excel workbook for both paths.
-- Using DB storage avoids MinIO interactions for exports in Phase 2.10.
-- Phase 3 may migrate large exports to MinIO storage.
--
-- Download is one-time: download_count is incremented on each serve and
-- the endpoint returns 410 once download_count >= 1. expires_at is set
-- when a job completes; requests after that also return 410.

create table export_jobs (
    id                   uuid primary key default gen_random_uuid(),
    export_scope         varchar(32) not null,
    scope_id             uuid,                              -- project/zone UUID; null for PAN_INDIA
    status               varchar(32) not null default 'QUEUED',
    created_by_user_id   uuid not null references users(id),
    file_name            varchar(256),
    file_data            bytea,                             -- populated when COMPLETED
    error_message        text,                              -- populated when FAILED
    download_count       integer not null default 0,
    expires_at           timestamptz,                       -- populated when COMPLETED
    created_at           timestamptz not null default now(),
    updated_at           timestamptz not null default now(),
    constraint chk_export_scope  check (export_scope in ('PROJECT', 'ZONE', 'PAN_INDIA')),
    constraint chk_export_status check (status in ('QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED'))
);

create index ix_export_jobs_status on export_jobs(status)
    where status in ('QUEUED', 'PROCESSING');

create trigger export_jobs_updated_at
    before update on export_jobs
    for each row execute function tg_set_updated_at();
