-- PIA Tracker — HRMS designations + default roles (repeatable migration).
-- Generated by ops/generate_user_migration.py.
-- New designations default to data-entry roles to satisfy
-- chk_designations_at_least_one_role. Default-role rules:
--   DY_* → ROLE_DY_CE_C, CE_* → ROLE_CE_C, new others → ROLE_APPROVER_GENERIC.

INSERT INTO designations
    (code, name, short_label, category, is_approval_role, is_data_entry_role, display_order, description)
VALUES
    ('CE_CON', 'CE/Con', 'CE/Con', 'CONSTRUCTION', false, true, 1000, 'CE/Con (imported from HRMS)'),
    ('DY_CE_GS', 'DY CE(GS)', 'DY CE(GS)', 'CONSTRUCTION', false, true, 1001, 'DY CE(GS) (imported from HRMS)'),
    ('EDGS_CIVIL_III', 'EDGS (CIVIL-III)', 'EDGS (CIVIL-III)', 'CONSTRUCTION', false, true, 1002, 'EDGS (CIVIL-III) (imported from HRMS)')
ON CONFLICT (code) DO NOTHING;

INSERT INTO designation_default_roles (designation_code, role_code)
VALUES
    ('CE_C', 'ROLE_CE_C'),
    ('CE_CON', 'ROLE_CE_C'),
    ('DY_CE', 'ROLE_DY_CE_C'),
    ('DY_CE_GS', 'ROLE_DY_CE_C'),
    ('EDGS_CIVIL_III', 'ROLE_EDGS_CI')
ON CONFLICT (designation_code, role_code) DO NOTHING;
